version: "3.3"
services:
  api:
    container_name: api
    image: "arsu663/webtech-project"
    build: 
        context: .
        dockerfile: DockerFile
    depends_on: 
        - db
    ports: 
        - 3030:3000
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    hostname: seekersgroup.live
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
       MYSQL_ROOT_PASSWORD: password
       PMA_HOST: db
       PMA_ARBITRARY: 1
       PMA_PORT: 3306
  db:
    image: mariadb:10.3
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dev_profile
      MYSQL_ROOT_HOST: '%'
    volumes:
      - app-db-data:/var/lib/mysql
volumes:
  app-db-data: